### ISSUE TITLE
v1.0.0 배포 전 수정 사항

### ISSUE THREAD

**Issue by kkn1125** [kkn1125/mkDocumentifyJS#56]
### 개선 대상과 문제

1. 검색창
   - 마크부분 띄어지는 현상
2. 사이드바
   - 모바일환경 반응형 되지 않음

### 솔루션

1. `.dropdown-content`를 감싸는 `#search-result`에 `flex`로 설정해서 공백없이 붙이면 좋을 것 같다는 생각
2. 그리드 설정을 `@media`로 너비에 맞춰서 `column`과 `row`를 조정

### 대안

대안 없음

### 추가 사항

추가 사항 없음

**Comment by ohoraming** [comment]
+ 검색창 -> 대소문자 입력 구분없이 결과값 검색되도록 하기

**Comment by kkn1125** [comment]
## 수정 예정

1. 채팅창 "만든 사람" 탭 클릭 후 나타나는 링크 클릭 안되는 버그 발견
   - `pointer-events: all;` 로 변경

#58 참조

**Comment by kkn1125** [comment]
의견 반영
