### ISSUE TITLE
최종 검토

### ISSUE THREAD

**Issue by kkn1125** [kkn1125/mkDocumentifyJS#63]
## 개선 사항

1. 채팅봇
   - 저장된 페이지 "저장"기능 제거
2. 검색창 결과 클릭
   -  해당 함수로 이동
   -  검색창 비우기

## 변경된 사항

1. 채팅봇
   - 딜레이 시간 단축 (1초)
   - 첫 안내메세지 "도와줘" 추가
   - 저장시 콘솔 제거
2. theme.js 즉시실행함수 함수명 받아오는 메서드 삭제
3. 원문 번호
   - 패딩 x축 0
   - 왼쪽 정렬
4. 사이드바 분할 저장시 gnb와 이격되는 현상
   -  gnb의 `align-items: center`추가 , `max-height` 제거

**Comment by kkn1125** [comment]
검색창 외 수정 7건 완료

**Comment by ohoraming** [comment]
검색창 결과 드롭다운에 원문 라인넘버와 파일명 표시 추가
